---
- name: Check if host needs reboot
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Check if /var/run/reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Report reboot requirement
      debug:
        msg: "Reboot is required on this host."
      when: reboot_required_file.stat.exists

    - name: Report no reboot required
      debug:
        msg: "No reboot is required on this host."
      when: not reboot_required_file.stat.exists